### ISSUE TITLE
position: left 在 hexo 不生效 

### ISSUE THREAD

**Issue by lixueninggg** [EYHN/hexo-helper-live2d#100]
1. 版本3.x 在hexo中的配置position不生效
2. 配置如下
```
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  model:
    use: live2d-widget-model-wanko
  display:
    position: left
    width: 150
    height: 300
  mobile:
    show: true
```

**Comment by lixueninggg** [comment]
@EYHN 请帮我看一下谢谢

**Comment by lixueninggg** [comment]
@Yggdrasill-7C9 这个是官方github的配置,不知道你用的是2.5.1版本还是3.x版本

**Comment by Yggdrasill-7C9** [comment]
@lixueninggg 我用的是3.x 版本，我找到原因了，是配置路径的问题。如果你没添加新的模型，用我下面的这个配置，脚本路径，插件路径，模型路径用默认的就好。
```
live2d:
  model:
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    superSample: 2
    width: 150
    height: 300
    position: left
    hOffset: 0
    vOffset: -20
  mobile:
    show: true
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2
```
