### ISSUE TITLE
人物有菱形碎片空白

### ISSUE THREAD

**Issue by poorpool** [EYHN/hexo-helper-live2d#117]
config in `_config.yml`:
`_config.yml` 中的配置:
我尝试了多种主题，所有的主题都是这种支离破碎的感觉……
下面的直接就是网站的config，不是theme的
```yaml
live2d:
  model:
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
    use: live2d-widget-model-hibiki
  display:
    superSample: 2
    width: 150
    height: 300
    position: left
    hOffset: 0
    vOffset: -20
  mobile:
    show: true
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2
```

## Description 问题描述
Screenshot(if have):
截图(如果有):
![pic](https://i.loli.net/2018/06/09/5b1b9323ebb64.png)

@EYHN @xiazeyu
