### ISSUE TITLE
在next和landscape主题中无法显示

### ISSUE THREAD

**Issue by phantom9999** [EYHN/hexo-helper-live2d#120]
**描述你的问题**
next: 5.1.4和landscope 中体中无法显示.

**复现步骤**
"hexo": "^3.2.0",
"hexo-helper-live2d": "^3.0.3",

出现问题的网站地址:
`_config.yml` 中的配置:

```yaml

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  model:
    use: live2d-widget-model-wanko
  display:
    position: right
    width: 30
    height: 60
  mobile:
    show: false
```

控制台输出:

1. 打开'...'
2. 双击'...'
3. 滑动到'...'
4. 发现'...'错误

**预期的行为**
请简明清晰地描述此操作预期的结果

**屏幕截图**
如果可能, 请添加一些屏幕截图来更好地描述你的问题

**环境信息(请务必填写下列信息)**
- 设备: [e.g. iPhone 6, PC]
- 操作系统: [e.g. iOS 8.1, Windows 10]
- 浏览器 [e.g. Chrome 66, Safari 11.2]
- hexo-helper-live2d: [e.g. 3.0.0]
> 使用 `npm ls hexo-helper-live2d` 来获取当前插件版本.

**额外的信息**
请在此处描述其他的内容

- [x] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] 我已仔细阅读[README](../README.md)中的相关内容。

> 将 `[ ]` 变为 `[x]` 来表示我接受了这些问题。

@EYHN @xiazeyu
