### ISSUE TITLE
live2d tag detected, but won't be use. Make sure 'tagMode' config is expected. See #36, #122.

### ISSUE THREAD

**Issue by callG** [EYHN/hexo-helper-live2d#123]
hexo/_config,yml配置如下：
```yml
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
```
运行`hexo g`时报告**HEXO-HELPER-LIVE2D**`: live2d tag detected, but won't be use. Make sure 'tagMode' config is expected. See #36, #122.`
