### ISSUE TITLE
模型加载不出来

### ISSUE THREAD

**Issue by lengyue1024** [EYHN/hexo-helper-live2d#127]
**描述你的问题**
在我的[博客](https://www.bingyublog.com)中加载不出来看板娘，我已经按照说明配置了。我在浏览器中调试，看到了如下的错误
![](https://ws1.sinaimg.cn/large/006DGX4tly1fv4pzdhztwj30og04r0t8.jpg)

出现问题的网站地址: www.bingyublog.com
`_config.yml` 中的配置:

```yaml

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-z16
  display:
    position: right
    width: 75
    height: 150
  mobile:
    show: false

```
**屏幕截图**
如果可能, 请添加一些屏幕截图来更好地描述你的问题
这是模型文件路径D:\Hexo\live2d_models\live2d-widget-model-z16\assets
![](https://ws1.sinaimg.cn/large/006DGX4tly1fv4q3kdjjkj30f7058aa8.jpg)
这是报错信息截图
![](https://ws1.sinaimg.cn/large/006DGX4tly1fv4q5d0uykj311o06l0ta.jpg)
![](https://ws1.sinaimg.cn/large/006DGX4tly1fv4q5rn2cnj311x0cgwgd.jpg)
**环境信息(请务必填写下列信息)**
- 设备: PC
- 操作系统: windows10
- 浏览器 firefox62.0
- hexo-helper-live2d: 3.1.0
> 使用 `npm ls hexo-helper-live2d` 来获取当前插件版本.

**额外的信息**
请在此处描述其他的内容

- [x] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] 我已仔细阅读[README](../README.md)中的相关内容。

> 将 `[ ]` 变为 `[x]` 来表示我接受了这些问题。

@EYHN @xiazeyu
