### ISSUE TITLE
加载不到 L2Dwidget.0.min.js  配置按步骤检查了很多遍，版本都是最新。

### ISSUE THREAD

**Issue by AnimatorBullet** [EYHN/hexo-helper-live2d#134]
**描述你的问题**

![_20190125023421](https://user-images.githubusercontent.com/45991057/51700840-0630ac80-204b-11e9-8021-341260d98b4c.png)

![_20190125023511](https://user-images.githubusercontent.com/45991057/51700829-003acb80-204b-11e9-9aff-481d3a384791.png)
这个路径加载应该是错误的吧。

![_20190125023644](https://user-images.githubusercontent.com/45991057/51700819-fc0eae00-204a-11e9-8bd2-75b4859e0821.png)
看了一些问题解答，这里前面应该还有东西没加载嘛。

我的配置如下，参照了他人改的使用模型。
模型是有正常加载，自定义和默认几个都试了。

最神奇的是，有时候本地部署预览改了某些插件参数，
会偶然蹦出来，但之后无论怎么改回一样参数都不再出现。。。

**复现步骤**
必现。。。
出现问题的网站地址: [](https://acebullet.tk/)
**将 `log` 选项设置为 `true` 来显示完整的日志.**
`_config.yml` 中的配置:

```yaml

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  model:
    use: kesshouban
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    superSample: 2
    width: 150
    height: 300
    position: left
    hOffset: 0
    vOffset: -20
  mobile:
    show: true
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2
```

控制台输出:

1. 打开'...'
2. 双击'...'
3. 滑动到'...'
4. 发现'...'错误

**预期的行为**
请简明清晰地描述此操作预期的结果

**屏幕截图**
如果可能, 请添加一些屏幕截图来更好地描述你的问题

**环境信息(请务必填写下列信息)**
- 设备: [PC]
- 操作系统: [Windows 10]
- 浏览器 [Chrome 70]
- hexo-helper-live2d: [3.1.0]
> 使用 `npm ls hexo-helper-live2d` 来获取当前插件版本.

**额外的信息**
请在此处描述其他的内容

- [x] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] 我已仔细阅读[README](../README.md)中的相关内容。

> 将 `[ ]` 变为 `[x]` 来表示我接受了这些问题。

@EYHN @xiazeyu
