### ISSUE TITLE
关于waifu-tips.js

### ISSUE THREAD

**Issue by Yanstory** [EYHN/hexo-helper-live2d#137]
在[这个](https://imjad.cn/archives/lab/add-dynamic-poster-girl-with-live2d-to-your-blog-02)页面里有供live2d使用的waifu-tips.js，可以给live2d小人添加（基于鼠标动作的）文字浮动框。

这个插件支持waifu-tips.js吗？或者怎样可以集成到插件里？

**Comment by EYHN** [comment]
### 很抱歉！让您久等了
我在 https://github.com/xiazeyu/live2d-widget.js/commit/d700ae349cc8ea254d08f4f246d5319e92155dad 实现了一个简单的 hitokoto 示例。
![image](https://user-images.githubusercontent.com/13579374/55391630-5a389f80-556c-11e9-9c86-83d2b7cc3045.png)

现在将你的 hexo-helper-live2d 升级到 3.1.1 ，然后如下修改设置，可以体验此功能
``` yaml
live2d:
  enable: true
  dialog:
    enable: true
    hitokoto: true
```

关于会话框后续更新请关注 https://github.com/xiazeyu/live2d-widget.js/issues/48

**Comment by yanickxia** [comment]
@EYHN 可否配置脚本，好像如下方式无效

```yaml
 dialog:
    enable: true
    hitokoto: true
    script:
      'every 2s': '$hitokoto'
      'tap face': 'text2'
      'tap body': 'text3'
```
