### ISSUE TITLE
我找不到assets路径。。。

### ISSUE THREAD

**Issue by jerrywcy** [EYHN/hexo-helper-live2d#142]
我用npm安装过了，装完就在node_modules文件夹下
但是没有assets文件夹。。。
配置如下：
```
# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  # enable: false
  scriptFrom: local # 默认
  pluginRootPath: node_modules/hexo-helper-live2d # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-koharu # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
```
是我少装了什么吗？
求助！

**Comment by jerrywcy** [comment]
live2d-widget-model-koharu我也装过了

**Comment by jerrywcy** [comment]
文件夹长这样：
![image](https://user-images.githubusercontent.com/34678939/61839727-415c4d00-aec1-11e9-84ed-6c8153d001b8.png)

**Comment by jerrywcy** [comment]
这太神奇了！
我删掉主题配置文件里的东西之后看板娘就出现了！！！

**Comment by jerrywcy** [comment]
但是不是我想要的。。。

**Comment by jerrywcy** [comment]
我想要的是koharu而不是shizuku。。。

**Comment by EYHN** [comment]
请把位置写在hexo根目录里的配置文件里

**Comment by jerrywcy** [comment]
？？？
我就是把配置删掉之后它就正常显示了。
删掉之前显示不了

**Comment by jerrywcy** [comment]
而且我安装了live2d-widget-koharu之后应该怎么办啊。。。
似乎那里有一个asset文件夹？

**Comment by jerrywcy** [comment]
![image](https://user-images.githubusercontent.com/34678939/61868330-c2403680-af0b-11e9-9a6b-0dc67601ad49.png)

**Comment by jerrywcy** [comment]
![image](https://user-images.githubusercontent.com/34678939/61868330-c2403680-af0b-11e9-9a6b-0dc67601ad49.png)

**Comment by jerrywcy** [comment]
![image](https://user-images.githubusercontent.com/34678939/61869411-22d07300-af0e-11e9-9d68-9510539920d9.png)
这样就显示不了了。

**Comment by xiazeyu** [comment]
请问您的主题配置文件是哪个?
开`debug: true`之后有没有什么提示?

**Comment by jerrywcy** [comment]
我的主题配置文件：
```
# Automatically Excerpt. Not recommand.
# Please use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: true

#logo
fa_logo: iconbattle-net iconfont

# Header
menu:
  主页: /
  归档: /archives
  标签: /tags
  分类: /categories
  炒鸡有趣的东西: /炒鸡有趣的东西

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url:
facebook_url:
instagram_url:
dribble_url:
github_url: https://github.com/klugjo/hexo-theme-alpha-dust
googleplus_url: https://plus.google.com/
behance_url:
fivehundredpx_url:
email_url: jerrymonkeynj@163.com
rss_url:

# Footer About Text
footer_about: "This theme was developed by <a href=\"https://github.com/klugjo\">Jonathan Klughertz</a>. The source code is available on Github. Create Websites. Make Magic."

# Footer Copyright Line
footer_copyright: "@Untitled. All right reserved | Design & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"

#MathJax
mathjax: true

# Post wordcount display settings
# Dependencies: https://github.com/willin/hexo-wordcount
word_count: true

# Favicon
favicon: /img/favricon.ico

#站内搜索
local_search:
    enable: true  #搜索开关
    location: "right: 50px;top: 30px;" #搜索框位置top/left/bottom/right
    facade: ""  #搜索框样式

#IconFont
iconfont:
    link: //at.alicdn.com/t/font_1312964_yvegk0sxj9g.css
```
