### ISSUE TITLE
安装了koharu，但显示的是shizuku

### ISSUE THREAD

**Issue by 9211314** [EYHN/hexo-helper-live2d#143]
# Issue
我按项目默认配置放入hexo的配置文件，应该是wanko，但网页显示的是shizuku。
改成koharu，并install了koharu，显示的还是shizuku。
所有配置都是按默认的，安装和配置也是在hexo根目录下。
这是配置代码：
```
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d-widget-model-koharu
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
  react:
    opacity: 0.7
```
[这是我的博客地址](https://www.woai.it)
这是配置环境截图：
![QQ截图20190725140946](https://user-images.githubusercontent.com/45234281/61850083-edb02a80-aee5-11e9-8a06-5d2f4a9f1a06.png)
