### ISSUE TITLE
模型live2d-widget-model-haruto，与busuanzi2.3不兼容

### ISSUE THREAD

**Issue by andus-top** [EYHN/hexo-helper-live2d#146]
**Describe the bug**

在使用live2d-widget-model-haruto模型后，<span id="busuanzi_container_site_pv">、<span id="busuanzi_container_site_uv">被设置样式：`style="display: none;"`

**To Reproduce**

1. 在ocean主题中，在footer.ejs中引入，busuanzi的代码段
`<% if (is_home()) { %>
<i class="fe fe-bar-chart"></i><span id="busuanzi_container_site_pv" > 访问量:<span id="busuanzi_value_site_pv"></span></span>
<%} %>
&emsp;<i class="fe fe-user"></i><span id="busuanzi_container_site_uv"> 访客数:<span id="busuanzi_value_site_uv"></span></span>&emsp;
<% if (is_post()) { %>
<i class="fe fe-bookmark"></i> 文章访问量:<span id="busuanzi_value_page_pv"></span>
<%} %>`

2.然后配置live2d的萌宠
```
live2d:
  enable: true
  scriptFrom: local
  model:
    use: live2d-widget-model-haruto
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    superSample: 2
    width: 150
    height: 300
    position: left
    hOffset: 0
    vOffset: -20
  mobile:
    show: true
  react:
    opacityDefault: 0.5
    opacityOnHover: 0.2
```

3.出现描述的问题

**Screenshots**

正确情况：
![image](https://user-images.githubusercontent.com/37007084/63758061-cafea080-c8ed-11e9-98ea-96371589e87d.png)
错误情况：
![image](https://user-images.githubusercontent.com/37007084/63757992-a9051e00-c8ed-11e9-910b-f6ab9931868e.png)

**Environment (please complete the following information):**

- Device:  PC
- OS: Windows 10
- Browser：Chrome 66
- "hexo-helper-live2d": "^3.1.1",
- "live2d-widget-model-haruto": "^1.0.5",

**Additional context**

- [x] I have alreday read instructions in [CONTRIBUTING](CONTRIBUTING.md).

- [x] I have alreday read instructions in [README](../README.md).

> Change the `[ ]` into `[x]` to show myacceptance.

@EYHN @xiazeyu
