### ISSUE TITLE
using the value opacityDefault and opacityOnHover of react has no effect 、使用react为opacityDefault和opacityOnHover没效果，但直接设置透明度就可以

### ISSUE THREAD

**Issue by wLove-c** [EYHN/hexo-helper-live2d#147]
**Describe the bug**
```
live2d:
  enable: true
  pluginModelPath: assets/
  model:
    use: live2d-widget-model-shizuku  
  display:
    position: left
    width: 300
    height: 600
  mobile:
    show: true  #是否在手机进行显示
    scale: 0.3
  react:
#     opacity: 0.7 # 透明度设置
    opacityDefault: 0.7
    opacityOnHover: 0.2

```

It is no effect that I use it as above；

**To Reproduce**

config in `_config.yml`:

```yaml

live2d:

```

URL:
**Turn `log` config to `true` to show verbose debug output.**
Console output:

4. See error of '...'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Device: [e.g. iPhone 6, PC]
- OS: [e.g. iOS 8.1, Windows 10]
- Browser [e.g. Chrome 66, Safari 11.2]
- hexo-helper-live2d: [e.g. 3.0.0]
> use `npm ls hexo-helper-live2d` to get current plugin's version.

**Additional context**

- [ ] I have alreday read instructions in [CONTRIBUTING](CONTRIBUTING.md).

- [ ] I have alreday read instructions in [README](../README.md).

> Change the `[ ]` into `[x]` to show myacceptance.

@EYHN @xiazeyu
