### ISSUE TITLE
live2d会覆盖我原有的样式么？

### ISSUE THREAD

**Issue by jelly54** [EYHN/hexo-helper-live2d#150]
**描述你的问题**
我在开启live2d后我站点的浏览统计就不显示了，关闭live2d浏览统计又开启了。请问如何使其不更改我原有的样式呢？

**复现步骤**
`
开启  会修改浏览统计标签为 display: none
live2d:
  enable: true  
` 

`
关闭 浏览统计又会出现
live2d:
  enable: false
`

出现问题的网站地址:  https://jelly54.github.io

**将 `log` 选项设置为 `true` 来显示完整的日志.**
`_config.yml` 中的配置:

```yaml
live2d:
  enable: true
  scriptFrom: local
  model:
    #use: live2d-widget-model-koharu
    use: live2d-widget-model-miku
    scale: 1
  display:
    position: right
    width: 200 
    height: 400
    hOffset: 0 
    vOffset: -5 
  mobile:
    show: true
    scale: 0.5
  react:
    opacity: 0.9
```

控制台输出:
Live2D 2.1.00_1
live2d.core.js:5913 profile : Desktop
live2d.core.js:5918   [PROFILE_NAME] = Desktop
live2d.core.js:5918   [USE_ADJUST_TRANSLATION] = false
live2d.core.js:5918   [USE_CACHED_POLYGON_IMAGE] = false
live2d.core.js:5918   [EXPAND_W] = 2

**预期的行为**
请简明清晰地描述此操作预期的结果

**屏幕截图**
开启live2d后
![](https://ftp.bmp.ovh/imgs/2019/10/5ead8fe6e40469f2.png)

关闭live2d后
![](https://ftp.bmp.ovh/imgs/2019/10/d752fbaca18a08eb.jpg)

**环境信息(请务必填写下列信息)**
- 设备: [ PC]
- 操作系统: [Windows 10]
- 浏览器 [版本 77.0.3865.120（正式版本） （64 位）]
- hexo-helper-live2d: [e.g. 3.1.1]
> 使用 `npm ls hexo-helper-live2d` 来获取当前插件版本.

**额外的信息**
请在此处描述其他的内容

- [x] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] 我已仔细阅读[README](../README.md)中的相关内容。

@EYHN @xiazeyu
