### ISSUE TITLE
hexo本地调试的时候有看板娘，部署到github仓库里便不显示了

### ISSUE THREAD

**Issue by csxiaoshang** [EYHN/hexo-helper-live2d#152]
**描述你的问题**
请简明清晰地描述您所遇到的问题
- npm 看板娘，在_config.yml 中model.user更改了配置，然后本地hexo s调试是没有问题的，右下角显示了看板娘，如下图
![image](https://user-images.githubusercontent.com/20570530/70026234-3b4a4b80-15da-11ea-8275-2ccc098a8906.png)
- 但是当hexo d部署到仓库csxiaoshang.github.io后，其他都显示正常，但是不显示看板娘。
报了L2Dwidget.min.js 404，如下图
![image](https://user-images.githubusercontent.com/20570530/70026406-aeec5880-15da-11ea-84ff-fc19a1668cca.png)

**复现步骤**
复现此问题的步骤
- 是根据说明来的，npm 模型，将配置复制到hexo站点的_config.yml中，修改model.use

出现问题的网站地址: https://csxiaoshang.github.io/
**将 `log` 选项设置为 `true` 来显示完整的日志.**
`_config.yml` 中的配置:

```yaml

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: node_modules/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-shizuku
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
  react:
    opacity: 0.7

```

控制台输出:

1. 打开'...'
2. 双击'...'
3. 滑动到'...'
4. 发现'...'错误

**预期的行为**
请简明清晰地描述此操作预期的结果

**屏幕截图**
如果可能, 请添加一些屏幕截图来更好地描述你的问题

**环境信息(请务必填写下列信息)**
- 设备: [ PC]
- 操作系统: [ubuntu 16.04]
- 浏览器 [ Chrome]
- hexo-helper-live2d: [3.1.1]
> 使用 `npm ls hexo-helper-live2d` 来获取当前插件版本.

**额外的信息**
请在此处描述其他的内容

- [x] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] 我已仔细阅读[README](../README.md)中的相关内容。

> 将 `[ ]` 变为 `[x]` 来表示我接受了这些问题。

@EYHN @xiazeyu
