### ISSUE TITLE
关于和不蒜子计数冲突的问题

### ISSUE THREAD

**Issue by BoyInTheSun** [EYHN/hexo-helper-live2d#161]
**描述你的问题**
我使用的是hexo的`hexo-theme-matery`主题，内置了不蒜子插件，已经正常配置使用。安装并开启live2d后不蒜子功能失效。

**复现步骤**
未安装live2d且不蒜子配置正常，执行`npm install --save hexo-helper-live2d`后，成功复现。
已安装live2d但`live2d.enable`为`false`，改为`true`后，成功复现。

出现问题的网站地址: boyinthesun.cn
主题中`_config.yml` 中的配置:
```yaml
# 只截取了相关配置
# 前端库
libs:
    js:
        busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次
```

根目录中`_config.yml` 中的配置:
```yaml
live2d:
    enable: true
    scriptFrom: local
    model: 
        use: live2d-widget-model-hijiki #模型选择
    display: 
        position: left  #模型位置
        width: 200       #模型宽度
        height: 300      #模型高度
    mobile: 
        show: false
```

**环境信息(请务必填写下列信息)**
- 设备: [PC]
- 操作系统: [Windows 10]
- 浏览器 [Chrome 76]
- hexo-helper-live2d: [3.1.]1

**额外的信息 部分HTML源码**
*正常时*
```HTML
<span id="busuanzi_container_site_pv">
    |&nbsp;<i class="far fa-eye"></i>&nbsp;总访问量:&nbsp;<span id="busuanzi_value_site_pv"
        class="white-color"></span>&nbsp;次
    </span>
<span id="busuanzi_container_site_uv">
    |&nbsp;<i class="fas fa-users"></i>&nbsp;总访问人数:&nbsp;<span id="busuanzi_value_site_uv"
        class="white-color"></span>&nbsp;人
    </span>
```
*异常时*
```HTML
<span id="busuanzi_container_site_pv" style="display: none;">
    |&nbsp;<i class="far fa-eye"></i>&nbsp;总访问量:&nbsp;<span id="busuanzi_value_site_pv" 
        class="white-color">2303950</span>&nbsp;次
</span>
<span id="busuanzi_container_site_uv" style="display: none;">
    |&nbsp;<i class="fas fa-users"></i>&nbsp;总访问人数:&nbsp;<span id="busuanzi_value_site_uv" 
        class="white-color">160644</span>&nbsp;人
</span>
```

- [x] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] 我已仔细阅读[README](../README.md)中的相关内容。

> 将 `[ ]` 变为 `[x]` 来表示我接受了这些问题。

@EYHN @xiazeyu
