### ISSUE TITLE
网页中无法展示live2d

### ISSUE THREAD

**Issue by Augists** [EYHN/hexo-helper-live2d#166]
hello

我通过`npm install lixxxxxxx-wanko` 安装的model

然后在themes里`_config.yml`内添加了如下代码

```
# live2d
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  model:
    use: live2d-widget-model-wanko
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    superSample: 2
    width: 150
    height: 300
    position: left
    hOffset: 0
    vOffset: -20
  mobile:
    show: true
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2

```

我设定在左边的wanko

但是出来的是右边的小姑娘

我是哪里做错了嘛

谢谢

- [ ] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] 我已仔细阅读[README](../README.md)中的相关内容。
