### ISSUE TITLE
小bug!  wanko身边有虚线...

### ISSUE THREAD

**Issue by lhalcyon** [EYHN/hexo-helper-live2d#89]
首先除夕夜作者发布了新版本,真的被感动到了!辛苦了!

但是新的版本怎么显示出来有虚线..而且大小默认的比以前大多了~ 

![](https://ws2.sinaimg.cn/large/006tNc79gy1fohjnf5jrhj30cm0iet9c.jpg)

**Comment by xiazeyu** [comment]
@lhalcyon 
这个是因为在依赖`live2d-widget`里我不小心把开发用版本发布到了npm上去..你可以用
```yml
live2d:
  dev:
    border: false
```
先关闭着..
或者`npm install`来更新一下新版本

**Comment by lhalcyon** [comment]
好的.解决了.多谢!  

再次表示作者辛苦了  狗年旺旺! ☺️

**Comment by xiazeyu** [comment]
@lhalcyon 
如果您的默认大小无法调整，请参阅README。
插件的设置发生了变动。大小需要在
```yml
live2d:
  display:
    widget: xxx
    height: xxx
```
中进行调整
