### ISSUE TITLE
NEXT 5.1.4 Gemini，有live2D文件生成，无模型

### ISSUE THREAD

**Issue by Xianbei233** [EYHN/hexo-helper-live2d#91]
### Expected behavior 预期行为
        正常npm安装，版本最新，应该有模型出现
### Actual behavior 实际行为
        正常安装，版本最新，无模型出现
### Steps to reproduce the behavior 复现步骤
       NEXT 5.1.4，gemini风格，静态文件生成时可见live2D相关文件生成，但实际部署与本机测试时皆不可见模型
     配置：
```
live2d:
  enable: true
  scriptFrom: local
  model:
    use: live2d-widget-model-wanko
  display:
    position: right
    width: 200
    height: 300
  mobile:
    show: false
```
部署页面:[点我](xianbei233.pw)

- [x ] I have alreday read instructions in [CONTRIBUTING](./CONTRIBUTING.md). 
我已仔细阅读[CONTRIBUTING](./CONTRIBUTING.md)中的相关内容。

> Change the `[ ]` into `[x]` to show your acceptance.
将 `[ ]` 变为 `[x]` 来表示你接受了这些问题。

@EYHN @xiazeyu
