### ISSUE TITLE
live2d tag was deprecated since 3.0. See #36. PLEASE REMOVE live2d TAG IN YOUR TEMPLATE FILE.

### ISSUE THREAD

**Issue by mengcarry** [EYHN/hexo-helper-live2d#92]
### Steps to reproduce the behavior 复现步骤

- [x] I have alreday read instructions in [CONTRIBUTING](./CONTRIBUTING.md). 
我已仔细阅读[CONTRIBUTING](./CONTRIBUTING.md)中的相关内容。

> Change the `[ ]` into `[x]` to show your acceptance.
将 `[ ]` 变为 `[x]` 来表示你接受了这些问题。

@EYHN @xiazeyu

**Comment by xiazeyu** [comment]
请从 layout/layout.ejs 或 layout/_layout.swig 中删掉 </body> 前的 {{ live2d() }} 或 <%- live2d() %>.

我们推荐您使用 npm install --save hexo-helper-live2d@3.x 来强制安装最新版本.

README里有写。

**Comment by mengcarry** [comment]
我装了最新版本，然后把layout.swig里的{{ live2d() }}删除之后，在_config.yml中加了live2d的配置就好使了，感谢！感谢！感谢！

**Comment by xiazeyu** [comment]
@donghuixin 不知道您所说的“那个live2d”指什么。
修改位置和尺寸可以通过修改`_config.yml`中的live2d设置实现。
https://l2dwidget.js.org/docs/class/src/index.js~L2Dwidget.html#instance-method-init
如
```yml
live2d:
  enable: true
    position: right
    width: 150
    height: 300
    hOffset: 0 # 改为你想要的水平偏移
    vOffset: 20 # 改为你想要的垂直偏移
```
