### ISSUE TITLE
About display on the hexo

### ISSUE THREAD

**Issue by cxyfreedom** [EYHN/hexo-helper-live2d#98]
## Description

About display on the hexo

### Expected behavior 预期行为

Display all hexo page

### Actual behavior 实际行为

Display only on the post page，not display on index page，tag page and so on

### Steps to reproduce the behavior 复现步骤

Version: 3.0.1

- [x] I have alreday read instructions in [CONTRIBUTING](./CONTRIBUTING.md).
  我已仔细阅读[CONTRIBUTING](./CONTRIBUTING.md)中的相关内容。

@EYHN @xiazeyu

**Comment by EYHN** [comment]
请提供你的配置文件，主题，log等信息

**Comment by cxyfreedom** [comment]
Theme:` NexT v6.0.6`
Node Version: `v8.10.0`

`_config.yml`

```
live2d:
  enable: true
  scriptFrom: jsdelivr
  model:
    use: https://cdn.jsdelivr.net/npm/live2d-widget-model-koharu@1.0.5/assets/koharu.model.json
  display:
    position: left
    width: 75
    height: 150
  mobile:
    show: true
  react:
    opacityDefault: 1
    opacityOnHover: 0.2
```
